Feature/oauth kakao
S-OSTeam/shop-api pull request #22
Opened 2023-11-17 11:50 UTC by sangcheol12

카카오 인증, unlink, user 정보 받아오는 api 제작
Test Code는 별도의 브랜치에서 작성

2023-11-19 06:23 UTC, chanil4129 commented on src/main/kotlin/sosteam/deamhome/domain/kakao/exception/KakaoTokenNotFoundException.kt
> +    override val message: String = "cannot recieve kako Token."
kakao

2023-11-19 06:45 UTC, chanil4129 commented on src/main/kotlin/sosteam/deamhome/domain/kakao/resolver/KakaoResolver.kt
> +    }
클라이언트 쪽에서 kakao 정보를 필요로 하는 경우가 있나?

2023-11-19 06:45 UTC, chanil4129 commented on src/main/kotlin/sosteam/deamhome/domain/kakao/service/KakaoService.kt
> +    }
네이버에도 unlink는 있어서 구현해야겠네. 땡큐

2023-12-21 10:13 UTC, sangcheol12 commented on src/main/kotlin/sosteam/deamhome/domain/kakao/resolver/KakaoResolver.kt
> +    }
이건 토큰 유효한지 검사하기 위해 만들었는데 해당 토큰에 맞는 Id값만 반환해요

2023-12-21 11:37 UTC, Hangeulkim requested changes

2023-12-21 11:37 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/kakao/dto/response/KakaoTokenReturnResponse.kt
> +data class KakaoTokenReturnResponse(
낙 타 좋 아

2023-12-22 04:19 UTC, merged