[#11] WishList 서비스 추가
S-OSTeam/shop-api pull request #26
Opened 2023-12-25 11:48 UTC by JooHui-void

Issue
---
- #11 

설명
---
- WishList 가지도록 Account 구조 변경
- WishList에 아이템 추가/ 삭제 기능 추가
- getAll로 전체 가져오기 추가

2023-12-26 21:41 UTC, Hangeulkim requested changes

2023-12-26 21:41 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/account/service/wishlist/WishListService.kt
> +    private val accountRepository: AccountRepository,
Crud를 찢어주세요

2023-12-26 21:41 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/account/entity/Account.kt
> +	private var faqs: ArrayList<String> = ArrayList()
Faq qna로 바꿔야 되긴하는데 내가 나중에 함

2023-12-26 21:41 UTC, Hangeulkim commented on src/main/resources/graphql/mutation.graphqls
> +    updateWishListItemInclude(userId: String,itemId: String ): [String]
Input은 request로 묶어주세여

2023-12-26 21:41 UTC, Hangeulkim commented on src/main/resources/graphql/query.graphqls
> +    getWishList(userId: String, page:Int): [ItemResponseDTO]
요건 type

2023-12-26 21:41 UTC, Hangeulkim commented on src/test/kotlin/sosteam/deamhome/domain/account/service/wishlist/WishListServiceTest.kt
> +            userId = "userId",
나중에 기본 설정으로 빠질꺼긴한데 내가 나중에 수정함

2023-12-27 12:00 UTC, JooHui-void commented on src/main/kotlin/sosteam/deamhome/domain/account/service/wishlist/WishListService.kt
> +    private val accountRepository: AccountRepository,
wishList 추가랑 삭제 묶어서 Modify 하나로 처리했습니다!

2023-12-27 12:51 UTC, JooHui-void commented on src/main/kotlin/sosteam/deamhome/domain/account/service/wishlist/WishListService.kt
> +    suspend fun addItem(account: Account, itemId: String ):Account{
다른 곳에서 쓸 수도 있지만 일단 private로 바꿔둡니다!

2024-01-05 13:00 UTC, Hangeulkim approved these changes

2024-01-05 13:00 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/account/service/wishlist/WishListReadService.kt
> +        val pageSize = 10
바꾸라고!!!!!!!!!!!!!

2024-01-05 13:00 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/account/handler/request/WishListRequestDTO.kt
> +data class WishListRequestDTO (
바꾸라고!!!!!!!!

2024-01-05 16:26 UTC, JooHui-void commented
할일~
---
- [ ] maxWishlistSize companion으로 빼기
- [ ] DTO 제거
- [ ] pageSize 변경 가능하게 수정

2024-01-06 13:57 UTC, merged