Feature/review
S-OSTeam/shop-api pull request #39
Opened 2024-01-21 16:39 UTC by chanil4129

2024-01-22 03:29 UTC, Hangeulkim requested changes

2024-01-22 03:29 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/review/handler/request/ReviewUpdateRequest.kt
> +	val images: List<String>,
이거 이미지는 변경이나 추가할 수도 있어서 그냥 String 처리하면 안됨.

2024-01-22 03:29 UTC, Hangeulkim commented on src/main/resources/graphql/review.graphqls
> +input ReviewCreateRequest{
이거 코드 valid grphaql에도 추가 해야댐

2024-01-22 03:29 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/review/handler/ReviewResolver.kt
> +	@QueryMapping
차라리 enum 같은 걸로 query 하나로 하는게 편하지 않을까?

2024-01-22 03:29 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/review/handler/ReviewResolver.kt
> +	@QueryMapping
review 검색할 때 해당 유저와 아이템으로 동시 검색할 수도 있으니 list로 받고

2024-01-22 15:18 UTC, JooHui-void requested changes
고생하셨습니다~~ :grin:

2024-01-22 15:18 UTC, JooHui-void commented on src/main/kotlin/sosteam/deamhome/domain/review/exception/ReviewIllegalArgumentIdException.kt
> +) : CustomGraphQLException(errorCode, ErrorType.NOT_FOUND, message) {
ErrorType.BAD_REQUEST 가 더 맞을 것 같네요!

2024-01-22 15:18 UTC, JooHui-void commented on src/main/kotlin/sosteam/deamhome/domain/review/handler/ReviewResolver.kt
> +			ITEM_ID -> reviewSearchService.searchReviewsByItemId(request)
enum값으로 받는거면 프론트에서 enum값을 알 수 있게 graphql에서 주석으로 알려줘야 할 것 같아요

2024-01-22 15:18 UTC, JooHui-void commented on src/main/kotlin/sosteam/deamhome/domain/review/handler/request/ReviewCreateRequest.kt
> +	@field: Size(max = 10, message = "제목 최대 길이는 10 입니다.")
10은 너무 짧지않나..? 아닐수도 있음

2024-01-22 15:18 UTC, JooHui-void commented on src/main/kotlin/sosteam/deamhome/domain/review/service/ReviewDeleteService.kt
> +		return ResponseEntity.ok("Review 제거 성공 : `${request.reviewId}` ")
soft delete라 아이템 없어도 제거 성공 반환할 것 같은데 상관은 없을지도?

2024-01-22 15:18 UTC, JooHui-void commented on src/main/kotlin/sosteam/deamhome/domain/review/handler/request/ReviewCreateRequest.kt
> +	val score: Double,
![image](https://github.com/S-OSTeam/shop-api/assets/69834729/02896424-60f2-487c-8dae-ebc6b0ffffb5)
피그마 보니까 리뷰 다는거 자체는 Integer이고 아이템 하나의 평균이 double같은데 확인한번 해주세요!

2024-01-22 15:18 UTC, JooHui-void commented on src/main/kotlin/sosteam/deamhome/domain/review/service/ReviewDeleteService.kt
> +		return ResponseEntity.ok("Review 제거 성공 : `${request.reviewId}` ")
아 그리고 삭제할 때 리뷰에 달린 이미지 더 안쓰면 지우는게 맞을듯!

2024-01-22 15:30 UTC, chanil4129 commented on src/main/kotlin/sosteam/deamhome/domain/review/handler/request/ReviewCreateRequest.kt
> +	@field: Size(max = 10, message = "제목 최대 길이는 10 입니다.")
30으로 고쳤으

2024-01-22 15:46 UTC, chanil4129 commented on src/main/kotlin/sosteam/deamhome/domain/review/handler/request/ReviewCreateRequest.kt
> +	val score: Double,
너 말이 맞는듯? 우선 Int로 고쳤어. 
근데 평균 내는거는 Item 엔티티에
```
@Transient
val reviewScore: Double
```
이런식으로 만들면 될거 같은데 맞지?

2024-01-23 03:21 UTC, Hangeulkim requested changes

2024-01-23 03:21 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/review/handler/ReviewResolver.kt
> +			REVIEW_ID -> listOf(reviewSearchService.searchReviewByReviewId(request))
아니 이거 그 뭐지 굳이 람다 안쓰고 그 repo에 booleanexpression 쓰면 됨미다 아니면 그냥 null 넘겨주면 자동으로 true로 가요

2024-01-23 03:21 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/review/handler/ReviewResolver.kt
> +			REVIEW_ID -> listOf(reviewSearchService.searchReviewByReviewId(request))
https://www.apollographql.com/blog/how-to-search-and-filter-results-with-graphql

2024-01-23 22:15 UTC, Hangeulkim requested changes

2024-01-23 22:15 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/review/repository/impl/ReviewRepositoryImpl.kt
> +		val predicate = BooleanBuilder()
만드는건 이렇게 하면 됨미다 그런데 이 로직이 재사용 되거나 엄밀히 말하면 find는 아니기에 이렁건 함수로 분리합시다

2024-01-23 22:15 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/review/service/ReviewSearchService.kt
> +			request.reviewId.forEach {
이거 in 쓰면 됨미다 querydsl에서

2024-01-23 22:15 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/review/service/ReviewUpdateService.kt
> +		if (ChronoUnit.MONTHS.between(createdAt, now) >= 1) {
이런 체크 로직은 search나 validation으로

2024-01-23 22:15 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/review/service/ReviewUpdateService.kt
> +		if (ChronoUnit.MONTHS.between(createdAt, now) >= 1) {
한달 리뷰 쪽에는 체크 로직이 없는거 같은데

2024-01-23 22:15 UTC, Hangeulkim commented on src/main/resources/graphql/review.graphqls
> +input ReviewSearchRequest{
이거 !박으면 필수 값입니다 null이 못들어와요

2024-01-24 08:37 UTC, chanil4129 commented on src/main/kotlin/sosteam/deamhome/domain/review/service/ReviewUpdateService.kt
> +		if (ChronoUnit.MONTHS.between(createdAt, now) >= 1) {
한달 뒤 후기랑 헷갈렸어..ㅋㅋㅋ 고쳤습니다!

2024-01-24 17:16 UTC, chanil4129 commented on src/main/kotlin/sosteam/deamhome/domain/review/service/ReviewUpdateService.kt
> +		if (ChronoUnit.MONTHS.between(createdAt, now) >= 1) {
다시 확인해보니깐 기능 명세서에
"아이템 리뷰 수정 기한 지정"라고 있던데 이거 한거였으.
맞지?

2024-02-26 09:11 UTC, closed without merging