Origin/feature/autholization mail
S-OSTeam/shop-api pull request #49
Opened 2024-02-04 03:43 UTC by sangcheol12

탈퇴 회원 이메일 전송

이메일 코드 인증

회원가입 이메일 인증
비밀번호 변경
아이디 조회
회원정보 변경
회원 복구
비밀번호 변경 로직

미작성 - 탈퇴 회원, 복구 회원 상태 변경
r2dbc로 변경 필요

2024-02-04 03:57 UTC, Hangeulkim requested changes

2024-02-04 03:57 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/account/entity/AccountStatus.kt
> +	var deletedAT: LocalDateTime? = LocalDateTime.now(),
At입니다

2024-02-04 03:57 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/account/service/AccountSendEmailService.kt
> +    private val randomStringService: RandomStringService,
Provider가 아니라 service로 해놨나...?

2024-02-04 03:57 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/account/service/AccountSendEmailService.kt
> +    private val sendMailService: SendMailService,
공통 서비스는 provider로!

2024-02-04 03:57 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/account/service/AccountSendEmailService.kt
> +    suspend fun sendChangePwdVerifyCode(userId: String): String {
이건 걍 하나로 묶으면 되지 않을까요? Send와 chk는 어차피 차이는 enum type인데 프론트에서 받으면 되지 않나요?

2024-02-04 03:57 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/account/service/AccountSendEmailService.kt
> +        val user = accountRepository.findAccountByUserId(userId)
이런 validate는 아마 validService엔가 만들어 놨을텐데

2024-02-04 03:57 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/account/service/AccountSendEmailService.kt
> +    suspend fun checkChangePwdVerifyCode(userId: String, code: String): String {
어차피 코드를 보낼때 계정 여부를 확인하는데 2차적으로 확인할 필요가 있나유?

2024-02-04 03:57 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/account/service/AccountSendEmailService.kt
> +        checkCodeByType(code, user.email, VerifyType.FINDUSERID)
보통 전부 대문자 전부 소문자인 경우 스네이크 케이스를 사용합니다 이렇게 다 대문자로 박으면 나중에 구분을 몬해요

2024-02-04 03:57 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/auth/handler/AccountAuthMailResolver.kt
> +    suspend fun checkSignupVerifyCode(
Check랑 validate를 언제 쓸지 네이밍 규칙도 정해야것네

2024-02-04 03:57 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/auth/handler/AccountAuthMailResolver.kt
> +    suspend fun checkChangePwdVerifyCode(
이런건 이렇게 함수 여러개로 만들면 알아보기가 힘듬미다 걍 하나로 만들고 enum switch case로 만드는게 훨씬 확장성이 좋아유

2024-02-04 03:57 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/global/attribute/VerifyType.kt
> +    SIGNUP, CHANGEPWD, FINDUSERID, CHANGEUSERINFO, RESTOREUSER
끼아아아아아아악 스네이크 붙여줘ㅓㅓㅓㅓㅓㅓ

2024-02-04 03:57 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/global/config/MailConfig.kt
> +    fun getJavaMailSender(): JavaMailSender {
이거 안만들어도 되지 않음?

2024-02-04 03:57 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/global/mail/RandomStringService.kt
> +class RandomStringService {
이거 뭐냐고 물어봐놓고 왜 또 만들었어!!!!!

2024-02-04 03:57 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/global/mail/SendMailService.kt
> +            println(e.message)
이건 절대 쓰시면 안됨미더 log를 공부하십시오

2024-02-04 03:57 UTC, Hangeulkim commented on src/main/resources/graphql/category.graphqls
> +directive @NotBlank(message : String = "graphql.validation.NotBlank.message") on ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION
이거 구조 다 바꼇는디 rebase 안된 듯?

2024-02-29 09:24 UTC, sangcheol12 commented on src/main/kotlin/sosteam/deamhome/domain/account/entity/AccountStatus.kt
> +	var deletedAT: LocalDateTime? = LocalDateTime.now(),
반영

2024-02-29 09:24 UTC, sangcheol12 commented on src/main/kotlin/sosteam/deamhome/domain/account/service/AccountSendEmailService.kt
> +    private val randomStringService: RandomStringService,
아차차

2024-02-29 09:24 UTC, sangcheol12 commented on src/main/kotlin/sosteam/deamhome/domain/account/service/AccountSendEmailService.kt
> +    private val sendMailService: SendMailService,
반영

2024-02-29 09:24 UTC, sangcheol12 commented on src/main/kotlin/sosteam/deamhome/domain/account/service/AccountSendEmailService.kt
> +    suspend fun sendChangePwdVerifyCode(userId: String): String {
반영

2024-02-29 09:25 UTC, sangcheol12 commented on src/main/kotlin/sosteam/deamhome/global/attribute/VerifyType.kt
> +    SIGNUP, CHANGEPWD, FINDUSERID, CHANGEUSERINFO, RESTOREUSER
반영

2024-02-29 09:25 UTC, sangcheol12 commented on src/main/kotlin/sosteam/deamhome/global/mail/RandomStringService.kt
> +class RandomStringService {
이거 전에 물어본건 Trow에 있는 코드고 여기는 없던데요?

2024-02-29 09:25 UTC, sangcheol12 commented on src/main/kotlin/sosteam/deamhome/global/mail/SendMailService.kt
> +            println(e.message)
넵!

2024-02-29 09:25 UTC, sangcheol12 commented on src/main/resources/graphql/category.graphqls
> +directive @NotBlank(message : String = "graphql.validation.NotBlank.message") on ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION
오잉?

2024-03-03 07:33 UTC, chanil4129 reviewed
고생 많으셨습니다~~

2024-03-03 07:33 UTC, chanil4129 commented on src/main/kotlin/sosteam/deamhome/domain/account/entity/AccountStatus.kt
> +	@Column("deleted_at")
LocalDateTime -> OffsetDateTime으로 바꾸기로 했어

2024-03-03 07:33 UTC, chanil4129 commented on src/main/kotlin/sosteam/deamhome/domain/auth/handler/request/AccountChangePwdRequest.kt
> +    @get:NotBlank(message = "<NULL> <EMPTY> <BLANK>")
@NotBlank graphqls 파일에 어노테이션 붙이기로 했슴다(다른 rqeust도 참조)
Pattern은 잘 모르겠네

2024-03-03 07:33 UTC, chanil4129 commented on src/main/kotlin/sosteam/deamhome/domain/auth/handler/AccountAuthMailResolver.kt
> +        @Argument @Valid request: SendVerifyCodeRequest
@Valid 삭제 (다른 resolver들도)

2024-03-03 10:07 UTC, sangcheol12 commented on src/main/kotlin/sosteam/deamhome/domain/auth/handler/request/AccountChangePwdRequest.kt
> +    @get:NotBlank(message = "<NULL> <EMPTY> <BLANK>")
확인

2024-03-03 10:08 UTC, sangcheol12 commented on src/main/kotlin/sosteam/deamhome/domain/account/entity/AccountStatus.kt
> +	@Column("deleted_at")
확인

2024-03-03 10:08 UTC, sangcheol12 commented on src/main/kotlin/sosteam/deamhome/domain/auth/handler/AccountAuthMailResolver.kt
> +        @Argument @Valid request: SendVerifyCodeRequest
넵! @Argument는 남기는거죠?

2024-03-03 10:19 UTC, Hangeulkim requested changes

2024-03-03 10:19 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/account/repository/AccountStatusRepository.kt
> +interface
이거 왜 가출했냐

2024-03-03 10:19 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/account/service/AccountSendEmailService.kt
> +        when (verifyType) {
이거 enum class 처럼 변수 여러개 넣으면 대

2024-03-03 10:19 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/account/service/AccountSendEmailService.kt
> +        when (verifyType) {
https://www.slipp.net/questions/563

2024-03-03 10:19 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/account/service/AccountValidService.kt
> +	suspend fun issueJwtToken(accountLoginDTO: AccountLoginDTO): TokenResponse {
이거 security에서 체크하지 않나?

2024-03-03 10:19 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/auth/handler/AccountAuthMailResolver.kt
> +        @Argument @Valid request: SendVerifyCodeRequest
gql이랑 조건 같으면 걍 놔둬도 될듯?

2024-03-03 10:19 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/global/mail/RandomStringService.kt
> +class RandomStringService {
뎃

2024-03-03 10:19 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/account/service/AccountChangePwdService.kt
> +class AccountChangePwdService(
왜 modify로 안하고 따로 만든거야?

2024-03-03 10:22 UTC, sangcheol12 commented on src/main/kotlin/sosteam/deamhome/domain/account/repository/AccountStatusRepository.kt
> +interface
띠용 제 폴더에는 있는데

2024-03-03 10:33 UTC, sangcheol12 commented on src/main/kotlin/sosteam/deamhome/domain/account/repository/AccountStatusRepository.kt
> +interface
엔터 눌려서 다른 파일이 바뀐듯?

2024-03-03 10:33 UTC, sangcheol12 commented on src/main/kotlin/sosteam/deamhome/domain/account/service/AccountSendEmailService.kt
> +        when (verifyType) {
신기하네여

2024-03-03 10:34 UTC, sangcheol12 commented on src/main/kotlin/sosteam/deamhome/domain/account/service/AccountValidService.kt
> +	suspend fun issueJwtToken(accountLoginDTO: AccountLoginDTO): TokenResponse {
실제로 그래서 사용도 안하고 일단 제가 만든게 아니라 완전 초창기부터 누가 만들어 놓고 안쓰는 메소드에요

2024-03-03 10:38 UTC, sangcheol12 commented on src/main/kotlin/sosteam/deamhome/domain/account/service/AccountChangePwdService.kt
> +class AccountChangePwdService(
modify서비스가 status 밖에 없어서 여기 넣어야 하나 했다 아닌거 같아서 새로 팠는데 넓게 쓰려면 AccountModifyService로 만들었어야 한듯
수정할게요

2024-03-04 08:15 UTC, merged