Feature/review rework
S-OSTeam/shop-api pull request #54
Opened 2024-02-26 05:48 UTC by chanil4129

2024-02-27 02:15 UTC, Hangeulkim requested changes

2024-02-27 02:15 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/log/entity/ReviewLikeLog.kt
> +	@Column("like_dislike")
이게 뭔소리여...?

2024-02-27 02:15 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/review/exception/ReviewUpdateExpiredException.kt
> +	errorCode: String = "UPDATE_EXPIRED",
이거 이렇게 적다 말면 뭔지 햇갈려요 차라리 class 명이랑 error code랑 일치시켜버려

2024-02-27 02:15 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/review/service/ReviewCreateService.kt
> +		item.avgReview = (item.avgReview * item.reviewCnt + request.score) / item.reviewCnt
이게 매번 리뷰마다 하는거라 걍 쿼리 짜는게 나을수도 있슴다 실 성능은 부하테스트 해봐야 암미더

2024-02-27 02:15 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/review/service/ReviewReportService.kt
> +		if (review.reportUsers.size >= 100) {
100개는 너무 많은듯...?

2024-02-27 02:15 UTC, Hangeulkim commented on src/main/kotlin/sosteam/deamhome/domain/review/service/ReviewValidService.kt
> +		// 7일 동안 최대 5회 신고
이건 없어도 될 듯 무차별 신고면 관리자가 죽이는쪽으로 미친놈이 일주일 5명보다 많으면 어째

2024-02-27 03:29 UTC, chanil4129 commented on src/main/kotlin/sosteam/deamhome/domain/log/entity/ReviewLikeLog.kt
> +	@Column("like_dislike")
like가 sql 예약어로 돼있어서 컬럼명 딴거로 했는데
"like_or_dislike" 이렇게 할까?

2024-02-27 03:32 UTC, chanil4129 commented on src/main/kotlin/sosteam/deamhome/domain/review/service/ReviewCreateService.kt
> +		item.avgReview = (item.avgReview * item.reviewCnt + request.score) / item.reviewCnt
확인

2024-02-27 03:34 UTC, chanil4129 commented on src/main/kotlin/sosteam/deamhome/domain/review/service/ReviewReportService.kt
> +		if (review.reportUsers.size >= 100) {
10개로 수정

2024-02-28 09:39 UTC, chanil4129 commented on src/main/kotlin/sosteam/deamhome/domain/review/service/ReviewValidService.kt
> +		val now = LocalDateTime.now()
확인. 아직 dev에 안바꼈길래 다들 충돌날까봐 일단 냅뒀음

2024-03-01 06:44 UTC, sangcheol12 approved these changes

2024-03-01 06:49 UTC, merged